(() => {
 'use strict';
 const $=s=>document.querySelector(s), scenes=[...document.querySelectorAll('.scene')],nav=[...document.querySelectorAll('[data-page]')],motion=matchMedia('(prefers-reduced-motion: reduce)');
 let current=0,busy=false,opened=false,drawTimer,hasDrawn=false,lastTurn=0;
 const root=$('#experience'),entrance=$('#entrance');root.inert=true;
 const guest=(new URLSearchParams(location.search).get('guest')||'Guest').trim().slice(0,80)||'Guest';$('[data-guest]').textContent=guest;if(guest!=='Guest')$('[name=name]').value=guest;
 function sync(){scenes.forEach((s,i)=>{s.inert=i!==current;s.setAttribute('aria-hidden',String(i!==current));s.classList.toggle('active',i===current)});nav.forEach((b,i)=>{if(i===current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('#previous').disabled=current===0;$('#next').disabled=current===4;scenes.forEach((s,i)=>document.body.classList.toggle('on-'+s.id,current===i))}
 function draw(replay=false){if(hasDrawn&&!replay)return;hasDrawn=true;window.playVenueDrawing?.();}
 async function go(index,animate=true){
  index=Math.max(0,Math.min(4,index));if(busy||index===current)return;busy=true;
  const from=scenes[current],to=scenes[index],forward=index>current;to.hidden=false;to.scrollTop=0;from.inert=true;to.inert=true;from.style.zIndex=forward?'2':'1';to.style.zIndex=forward?'1':'2';const turning=forward?from:to;turning.classList.add('turning');
  if(animate&&!motion.matches&&turning.animate){const frames=forward?[{transform:'rotateY(0deg)',opacity:1},{transform:'rotateY(-105deg)',opacity:.9}]:[{transform:'rotateY(-105deg)',opacity:.9},{transform:'rotateY(0deg)',opacity:1}];try{await turning.animate(frames,{duration:1150,easing:'cubic-bezier(.45,0,.15,1)'}).finished}catch{}}
  from.hidden=true;turning.classList.remove('turning');from.style.zIndex='';to.style.zIndex='';current=index;sync();busy=false;lastTurn=performance.now();history.replaceState(null,'','#'+to.id);const heading=to.querySelector('h2');heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});if(index===3)draw();
 }
 let openingTimer;
 function finishEntrance(){clearTimeout(openingTimer);entrance.classList.add('finished');entrance.inert=true;entrance.setAttribute('aria-hidden','true');root.inert=false;document.body.classList.remove('arriving');const desired=scenes.findIndex(s=>s.id===location.hash.slice(1));if(desired>=0&&desired!==current)go(desired,false);else{const heading=scenes[current].querySelector('h2');heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true})}}
 function enter(animate=true){if(opened){if(!animate)finishEntrance();return}opened=true;document.body.classList.add('entered');document.body.classList.toggle('instant-opening',!animate||motion.matches);if(animate&&!motion.matches)document.body.classList.add('arriving');entrance.classList.add('opening');openingTimer=setTimeout(finishEntrance,animate&&!motion.matches?4250:0)}
 $('#open').addEventListener('click',()=>enter());$('#skip').addEventListener('click',()=>enter(false));$('#replay').addEventListener('click',()=>{if(busy)return;opened=false;root.inert=true;entrance.inert=false;entrance.removeAttribute('aria-hidden');entrance.classList.remove('finished','opening');document.body.classList.remove('entered','arriving','instant-opening');$('#open').focus()});
 $('#next').addEventListener('click',()=>go(current+1));$('#previous').addEventListener('click',()=>go(current-1));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>go(current+1)));nav.forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.page))));$('.monogram').addEventListener('click',e=>{e.preventDefault();go(0)});window.addEventListener('hashchange',()=>{const i=scenes.findIndex(s=>s.id===location.hash.slice(1));if(opened&&i>=0)go(i)});
 function scrollable(target,delta){let n=target instanceof Element?target:null;while(n&&n!==document.body){const css=getComputedStyle(n);if(/auto|scroll/.test(css.overflowY)&&n.scrollHeight>n.clientHeight+2&&((delta>0&&n.scrollTop+n.clientHeight<n.scrollHeight-3)||(delta<0&&n.scrollTop>3)))return true;n=n.parentElement}return false}
 let wheel=0,wheelAt=0;window.addEventListener('wheel',e=>{if(!opened||root.inert||e.ctrlKey||Math.abs(e.deltaX)>Math.abs(e.deltaY)||scrollable(e.target,e.deltaY))return;e.preventDefault();if(busy||performance.now()-lastTurn<350)return;const now=performance.now();if(now-wheelAt>180)wheel=0;wheelAt=now;wheel+=e.deltaY*(e.deltaMode===1?16:1);if(Math.abs(wheel)>45){go(current+Math.sign(wheel));wheel=0}},{passive:false});
 let touch=null;window.addEventListener('touchstart',e=>{if(e.touches.length===1)touch={x:e.touches[0].clientX,y:e.touches[0].clientY,target:e.target,time:performance.now()}},{passive:true});window.addEventListener('touchend',e=>{if(!touch||!opened||root.inert||busy)return;const p=e.changedTouches[0],dy=touch.y-p.clientY,dx=touch.x-p.clientX;if(Math.abs(dy)>60&&Math.abs(dy)>Math.abs(dx)&&performance.now()-touch.time<900&&!scrollable(touch.target,dy)&&!touch.target.closest('input,textarea,select,button,a'))go(current+Math.sign(dy));touch=null},{passive:true});
 document.addEventListener('keydown',e=>{if(!opened||root.inert||e.target.closest('input,textarea,select,button'))return;if(['ArrowDown','ArrowRight','PageDown'].includes(e.key)){e.preventDefault();go(current+1)}if(['ArrowUp','ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(4)}});
 $('#redraw').addEventListener('click',()=>draw(true));
 $('#rsvp').addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const data=new FormData(e.target);$('#reply-text').textContent=`Dear Naveen & Dulanjani,\n\n${data.get('name')} — ${data.get('attendance')}.\nGuests: ${data.get('attendance')==='Regretfully declines'?'0':data.get('guests')}${data.get('note')?'\n\n'+data.get('note'):''}`;$('#prepared').hidden=false;$('#reply-status').textContent='Your demo reply is ready to copy. Nothing has been sent.';$('#prepared').scrollIntoView({block:'nearest',behavior:motion.matches?'auto':'smooth'})});
 $('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#reply-text').textContent);$('#reply-status').textContent='Copied. You can paste your reply into a message.'}catch{const range=document.createRange();range.selectNodeContents($('#reply-text'));getSelection().removeAllRanges();getSelection().addRange(range);$('#reply-status').textContent='Select and copy the highlighted reply.'}});
 $('#calendar').addEventListener('click',()=>{const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Naveen Dulanjani//Demo//EN','BEGIN:VEVENT','UID:nd-demo-20261018@invitation.local','DTSTAMP:20260911T000000Z','DTSTART:20261018T103000Z','DTEND:20261018T160000Z','SUMMARY:Naveen and Dulanjani - DEMO date','LOCATION:Avenra Gardens Negombo','DESCRIPTION:Placeholder date. Confirm with the couple before making plans.','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='naveen-dulanjani-demo.ics';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)});
 let audio,timer,soundOn=false;function stop(){clearInterval(timer);soundOn=false;$('#music').setAttribute('aria-pressed','false');$('#music').setAttribute('aria-label','Turn music on');audio?.suspend()}
 $('#music').addEventListener('click',async()=>{if(soundOn){stop();return}const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audio=audio||new A();await audio.resume();soundOn=true;$('#music').setAttribute('aria-pressed','true');$('#music').setAttribute('aria-label','Turn music off');const chime=()=>{[261.63,329.63,392,523.25].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.5;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.025,t+.08);g.gain.exponentialRampToValueAtTime(.0001,t+3.7);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+4)})};chime();timer=setInterval(chime,6500)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&soundOn)stop()});sync();if(new URLSearchParams(location.search).get('preview')==='1')enter(false);
})();
